# Generated by Django 5.1.1 on 2024-09-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletag_articlescope_article_scopes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='name',
            new_name='tag',
        ),
    ]
