# Generated by Django 5.1.1 on 2024-09-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_articlescope_scope_rename_articletag_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='scope',
            new_name='tag',
        ),
    ]
